### ISSUE TITLE
My Blockies image is wrong. What should I do?

### ISSUE THREAD

**Issue by daltonclaybrook** [Boilertalk/BlockiesSwift#2]
This is probably all my fault and not a problem with BlockiesSwift. I am using the library to show an image representation of my Ethereum address. I have called the initializer with my address just as is described in the README:

    Blockies(seed: "0xc78974Ea82202F0FBA3ED78490e591A3ff17D534")

This produces an image like this:

<img width="145" alt="screen shot 2018-10-09 at 8 26 41 am" src="https://user-images.githubusercontent.com/1727803/46669381-43a52300-cb9d-11e8-9c46-16f9d8099dfc.png">

However, when I enter this address on another site that uses blockies, such as Etherscan, I see an image like this:

<img width="151" alt="screen shot 2018-10-09 at 8 36 16 am" src="https://user-images.githubusercontent.com/1727803/46669801-78fe4080-cb9e-11e8-9c74-9296acf9de43.png">

What am I doing wrong? Do you have any suggestions for me to try?

**Comment by koraykoska** [comment]
The address has to be lowercased before being used as the seed. Do this and
you will get the same result as on Etherscan.

**Comment by daltonclaybrook** [comment]
It works! Thanks so much.

**Comment by ronaldoguedess** [comment]
Maybe you should add it on the DOC that we must use lowercased... after discovery it it works fine. Thanks

**Comment by koraykoska** [comment]
@ronaldoguedess you can open a PR to add it to the README.md
